services:
  orchestrator:
    build: .
    hostname: orchestrator
    entrypoint: "./orchestrator"
    ports:
      - 8080:8080
    configs:
      - config.toml
  agent:
    build: .
    entrypoint: "./agent"
    depends_on:
      - orchestrator
    configs:
      - config.toml
    restart: always

configs:
  config.toml:
    file: ./config.toml